# Generated by Django 3.0.6 on 2020-05-13 06:44

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_admin', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='device',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='device',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
