# Generated by Django 3.0.6 on 2020-05-13 07:03

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_admin', '0004_auto_20200513_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
