# Generated by Django 3.0.6 on 2020-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_admin', '0005_auto_20200513_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_class', models.ManyToManyField(to='bravo_admin.User')),
            ],
        ),
    ]
