# Generated by Django 3.0.6 on 2020-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_admin', '0006_tutorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_class',
            new_name='Student',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='Teacher',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
