# Generated by Django 3.0.6 on 2020-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_admin', '0007_auto_20200513_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Teacher',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
