# Generated by Django 3.0.6 on 2020-05-13 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_admin', '0008_auto_20200513_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='room',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='subject',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
